name: Check chronicl.md Update

on:
  pull_request:
    paths:
      - '**/*'

jobs:
  check-chronicl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if chronicl.md is updated
        run: |
          if ! git diff --name-only origin/${{ github.event.pull_request.base.ref }} | grep -q '^chronicl.md$'; then
            echo "Error: chronicl.md has not been updated in this pull request."
            exit 1
          fi